"""add metadata for message

Revision ID: 31f01d047020
Revises: 26d89ab7e4f0
Create Date: 2026-05-04 15:42:17.402655
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '31f01d047020'
down_revision = '26d89ab7e4f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "messages",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )

    op.execute(
        sa.text("""
            UPDATE messages
            SET metadata = '{}'::jsonb
            WHERE metadata IS NULL
        """)
    )

    op.alter_column(
        "messages",
        "metadata",
        nullable=False,
        server_default=None,
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'metadata')
    # ### end Alembic commands ###
