"""empty message

Revision ID: 46aa89470a39
Revises: 7387778fecda
Create Date: 2026-04-26 21:56:58.864349
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46aa89470a39'
down_revision = '7387778fecda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_forwarded_from_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reference_message_id'), table_name='messages')
    op.create_foreign_key(None, 'messages', 'messages', ['reference_message_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'messages', ['forwarded_from_message_id'], ['id'])
    op.add_column('participants', sa.Column('unread_messages_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'unread_messages_count')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_index(op.f('ix_messages_reference_message_id'), 'messages', ['reference_message_id'], unique=False)
    op.create_index(op.f('ix_messages_forwarded_from_message_id'), 'messages', ['forwarded_from_message_id'], unique=False)
    # ### end Alembic commands ###
