"""init

Revision ID: d8c9bebdee09
Revises: 20260410_0001
Create Date: 2026-04-10 23:15:16.920143
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c9bebdee09'
down_revision = '20260410_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('last_read_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'last_read_message_id')
    # ### end Alembic commands ###
